name:                sudoku
version:             0.1.0.0
github:              "somnus0208/sudoku"
license:             Apache
author:              "Chenyang Pan"
maintainer:          "chenyangp@acm.org"
copyright:           "2018 Chenyang Pan"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/somnus0208/sudoku#readme>

dependencies:
- base >= 4.7 && < 5
- parsec
- split
- parsec-numbers
- process
- temporary
- directory
- containers

library:
  source-dirs: src

executables:
  sdks:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sudoku

tests:
  sdks-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sudoku
